-- COMMUNITY MODERATION — repo mirror. Live objects are in Supabase.
--
-- HOW IT WORKS. Two BEFORE INSERT triggers, trg_mod_channel on channel_messages and trg_mod_dm on
-- dm_messages, both call st_mod_check(body). A non-null reason writes a row to mod_log AND returns
-- null, so the message is BLOCKED — never posted, not hidden-then-reviewed. mod_log is admin-only
-- (RLS policy mod_log_admin, USING st_is_admin()) and is read in Community from openModLog().
-- NOTE: live_messages (the live-session chat) has NO moderation trigger.
--
-- TWO SIGNALS, and both were too loose until 6 Sep 2026. A bare "100%" counted as a profit claim
-- and the bare word "deposit" counted as a contact push, so
--   "I am 100% sure I should not have moved my stop, going to deposit more on Monday"
-- was blocked. In a forex community those are two of the most ordinary words there are. Each
-- signal now needs wording that only appears when somebody is SELLING: bare deposit, sign up,
-- telegram, whatsapp, risk-free, profit split and copy trading no longer count on their own — a
-- prop firm has a profit split, a break-even trade is risk-free, "join the session" is not a
-- solicitation.
--
-- \y, NOT \b. PostgreSQL POSIX regex reads \b as BACKSPACE. A pattern ending "me\b" matches
-- nothing at all, which silently let "whatsapp me", "message me on telegram" and "deposit with me"
-- through. Anything word-boundary here must use \y.
--
-- [^.!?] in the claim patterns keeps a match inside one sentence, so two unrelated clauses cannot
-- combine across a full stop.
--
-- Verified 6 Sep 2026 against 11 scam and 15 ordinary messages: 11/11 caught, 15/15 passed, no
-- false positives. Re-run that set after any edit — the failure mode here is silent in both
-- directions.

-- 2026-09-06, LIVE CHAT COVERED. trg_mod_live on live_messages calls st_mod_live(), which blocks
-- and logs exactly as the other two do. It was the last gap and arguably the worst one: the live
-- chat is the busiest room in the app while a session runs, and the one a stranger is most likely
-- to walk into.
--
-- live_messages does not match the other two tables - the author is user_id not sender_id, there
-- is no sender_name column, and it belongs to a session not a channel. So mod_log gained
-- session_id, and st_mod_live resolves the display name at write time from journals.data->>
-- 'userName', falling back to profiles.email and then the uuid. A flagged row that cannot name who
-- wrote it is close to useless when deciding whether to act on somebody.
--
-- Verified end to end against the live table, then cleaned up: an ordinary message inserted
-- normally (this is the path EVERY live message takes - a runtime error in the trigger would break
-- live chat entirely, not just scams), a scam message returned zero rows and appeared in mod_log
-- as source 'live' with sender_name resolved to "Nestor". Both probe rows deleted; mod_log back to
-- 0 and live_messages back to 23.

-- 2026-09-06, SPANISH. The claim + push layer was English words only, so ZERO of eight realistic
-- Spanish scams were caught. The hard signals (t.me link, wallet address) are language-independent
-- and always fired, but "Ganancias garantizadas, escríbeme por privado" walked straight through.
--
-- Worse than a plain gap, because chat translation is DISPLAY-ONLY: _trCache is an in-memory client
-- cache, there is no stored translated column, and nothing writes a translation back. So the
-- trigger always sees the original text — which meant a Spanish pitch was stored unchecked and then
-- rendered into fluent English for every English reader. The feature that makes the community
-- bilingual was delivering the scam.
--
-- ACCENTS ARE FOLDED with translate(t, 'áéíóúüñ', 'aeiouun') rather than by installing unaccent.
-- Spanish is the only other language here and the mapping is seven characters, so folding inline
-- avoids an extension dependency. It also means "escribeme" and "escríbeme" are one pattern, which
-- matters because scammers type without accents constantly. ASCII is untouched, so every English
-- pattern behaves exactly as before.
--
-- Grammar mattered more than vocabulary in two places:
--   "duplicar MI cuenta" is an ordinary goal, "duplico TU dinero" is a pitch — only the second is
--   a hard signal. Likewise "únete a LA sesión" is an invitation, "únete a MI grupo" is a push.
--
-- Promising to send back a MULTIPLE of what you receive is now a claim in both languages
-- ("te devuelvo el triple", "give you back double"). Deliberately NOT treating "asking for crypto"
-- as a hard signal on its own: "send me the btc chart" is a normal request here.
--
-- Also fixed: the legacy base58 wallet pattern ran against the LOWERCASED text, so any address
-- containing a capital L failed — lowercased it becomes 'l', which that character class excludes.
-- It now runs against the original text, the only way that class can work.
--
-- Verified 6 Sep 2026: 18 scams (Spanish accented, Spanish unaccented, English) all caught;
-- 20 ordinary messages in both languages all passed. No misses, no false positives.

-- 2026-09-07, REACTIONS FOLLOW CHANNEL ACCESS, not posting rights or paid status.
-- Two things were stopping an emoji being easier to give than a paragraph:
--   * st_is_member() is "is_paid or comp", written before trials had community access. A trial
--     member can post in session-chat, report-bugs and app-suggestions but could not react in any
--     of them - the UI offered the picker and the insert was silently refused - and cr_select had
--     the same gate, so every message appeared to have no reactions at all.
--   * On the four review channels the CLIENT gated reactions on post_policy, so unticking "Who can
--     post" removed reactions too, for paying members included.
-- cr_insert and cr_select now test st_can_access on the reaction's own channel_id. The client gate
-- moved from _canPostHere() to _chanLocked(cur), so both sides ask the same question.
--
-- BANNED USERS ARE NOW BLOCKED, which they were not: channel_reactions never had the ban_block
-- policy its sibling tables carry, and st_is_member() had been holding the door shut for some of
-- them by accident. Widening access without this would have opened a hole rather than left one.
--
-- roles and member_roles moved to "any signed-in user" for SELECT. They are badge names, already
-- public on the pricing page, and gating them meant a trial saw the roster with every badge
-- missing. Writing them stays admin-only, which is the part that matters.
--
-- Verified as real accounts against the live policies, then rolled back:
--   trial reacting on a review post          ALLOWED
--   trial reacting in session-chat           ALLOWED
--   trial reacting where it cannot see       REFUSED
--   trial reading roles / member_roles       7 / 20  (was 0 / 0)
--   comp reacting on a review post           ALLOWED
